server:
  port: 2157

spring:
  datasource:
    driver-class-name: org.apache.hive.jdbc.HiveDriver
    url: jdbc:hive2://192.168.1.123:10000/test
    username:
    password:

mybatis-plus:
  mapper-locations: classpath*:mapper/ynyc_dm/*.xml